require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
project 'OrigensTesting.xcodeproj'

target 'OrigensTesting' do
  use_unimodules!
  config = use_native_modules!
  
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'Stripe', '~> 21.3.1'

  use_react_native!(:path => config["reactNativePath"])

#   post_install do |pi|
#     pi.pods_project.targets.each do |t|
#       t.build_configurations.each do |config|
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#       end
#     end
# end

end

target 'OrigensTestingClip' do
  use_unimodules!
  config = use_native_modules!
  
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'Stripe', '~> 21.3.1'

  use_react_native!(:path => config["reactNativePath"])

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
end
