name: Deploy to staging app
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g yarn
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Test packages
        run: yarn test:ci

  test-e2e:
    name: E2E Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g react-native-cli
          npm install -g detox-cli
          npm install -g yarn
      - name: Install Detox
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Install Pod Dependencies
        run: cd ./ios && pod install && cd ..
      - name: Detox Build
        run: detox build --configuration ios.sim.release
      - name: Detox Test
        run: detox test --configuration ios.sim.release --cleanup

  push-to-stg-app:
    needs: [test-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g yarn
          npm install -g expo-cli

      - name: Install Yarn Dependencies
        run: yarn install

      - name: Login to expo
        run: npx expo login --non-interactive -u origens
        env:
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Publish to stg
        run: yarn publish:stg --non-interactive
