name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  push-to-stg-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Install expo-cli
        run: npm install --save-dev expo-cli

      - name: Login to expo
        run: npx expo login --non-interactive -u origens
        env:
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Publish to stg
        run: yarn publish:stg --non-interactive
